{{- if and .Values.ingress.enabled .Values.ingress.customIssuer.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-giantswarm-nginx
spec:
  acme:
    email: accounts@giantswarm.io
    privateKeySecretRef:
      name: letsencrypt-giantswarm-nginx
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        acmeDNS:
          host: {{ .Values.ingress.customIssuer.acmeDnsHost }}
          accountSecretRef:
            name: {{ .Values.ingress.customIssuer.acmeDnsSecretName }}
            key: {{ .Values.ingress.customIssuer.acmeDnsSecretKey }}
{{- end }}
