global:
  apps:
    certManager:
      values:
        config:
          apiVersion: controller.config.cert-manager.io/v1alpha1
          enableGatewayAPI: true
          kind: ControllerConfiguration
  connectivity:
    availabilityZoneUsageLimit: 3
    certManager:
      useDnsChallenges: true
    network: {}
    topology: {}
  controlPlane: {}
  metadata:
    description: Test load testing setup
    name: ${WC}
    organization: giantswarm
    preventDeletion: false
  nodePools:
    nodepool0:
      availabilityZones:
      - ${AZ}
      instanceType: ${INSTANCE_TYPE}
      maxSize: ${MAX_NODES}
      minSize: ${MIN_NODES}
      rootVolumeSizeGB: 8
  providerSpecific: {}
  release:
    version: ${RELEASE}
